export const OPEN_AI_TOKEN = process.env.OPEN_AI_TOKEN
export const POCKETBASE_URL = process.env.POCKETBASE_URL
export const POCKETBASE_ADMIN_EMAIL = process.env.POCKETBASE_ADMIN_EMAIL
export const POCKETBASE_ADMIN_PASSWORD = process.env.POCKETBASE_ADMIN_PASSWORD